function [fitresult, gof] = createFits(X, fX)
%CREATEFITS(X,FX)
%  Create fits.
%
%  Data for 'Poly 1' fit:
%      X Input : X
%      Y Output: fX
%  Data for 'poly 2' fit:
%      X Input : X
%      Y Output: fX
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Mar-2017 14:46:22

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 2, 1 );
gof = struct( 'sse', cell( 2, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'Poly 1'.
[xData, yData] = prepareCurveData( X, fX );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Poly 1' );
h = plot( fitresult{1}, xData, yData);
% legend( h, 'fX vs. X', 'Poly 1', 'Location', 'NorthEast' );
% Label axes
xlabel X
ylabel fX
grid on
hold on
%% Fit: 'poly 2'.
[xData, yData] = prepareCurveData( X, fX );

% Set up fittype and options.
ft = fittype( 'poly2' );

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft );

% Plot fit with data.
%figure( 'Name', 'poly 2' );
h2 = plot( fitresult{2},'b');
legend('fX vs. X','poly 1', 'poly 2');
% Label axes
xlabel X
ylabel fX
grid on


